# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
#     xcode_select "/Applications/Xcode_10.3.app"
    create_keychain(
      name: "fastlanechain",
      default_keychain: true,
      unlock: true,
      timeout: false,
      lock_when_sleeps: false,
      password: "some_weak_pw"
    )
    match(type: "appstore",
#    match(type: "development",
      readonly: true,
      app_identifier: "de.havogt.flutter",
      keychain_name: "fastlanechain",
      keychain_password: "some_weak_pw"
    )
    update_project_provisioning(
      xcodeproj: 'Runner.xcodeproj',
      target_filter: 'Runner',
      build_configuration: 'Release',
#      profile: ENV['sigh_de.havogt.flutter_development_profile-path'],
      profile: ENV['sigh_de.havogt.flutter_appstore_profile-path'],
      code_signing_identity: 'iPhone Distribution',
    )
    update_project_team(
      path: "Runner.xcodeproj",
      teamid: "6NBT8Z3J37"
    )
#     TODO the following needs login...
#     increment_build_number(
#       build_number: latest_testflight_build_number + 1,
#       xcodeproj: "Runner.xcodeproj"
#     )
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      codesigning_identity: "iPhone Distribution"
    )
    match(type: "appstore",
      readonly: true,
      app_identifier: "de.havogt.flutter",
      keychain_name: "fastlanechain",
      keychain_password: "some_weak_pw"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      apple_id: "1525278983"
    )
  end
end
