name: debug
on:
  workflow_dispatch

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install fastlane
      run: |
        gem install bundler:1.17.2
        cd ios
        bundle install
