name: debug
on:
  workflow_dispatch

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup git
      run: |
        git config --global user.name "Hannes Vogt"
        git config --global user.email "vogt@hey.com"
    - name: Install fastlane
      run: |
        gem install bundler:1.17.2
        cd ios
        bundle install
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
