name: ios deploy
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install fastlane
      run: |
        gem install bundler:1.17.2
        cd ios
        bundle install
    - uses: subosito/flutter-action@v1
      with:
        channel: "stable"
    - name: Build ios
      run: |
        flutter pub get
        flutter packages get
        flutter build ios --release --no-codesign
    - name: Run Fastlane
      env:
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        MATCH_PASSWORD: ${{ MATCH_PASSWORD }}
      run: |
        cd ios
        bundle exec fastlane beta
