name: ios deploy
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install fastlane
      run: |
        gem install bundler:1.17.2
        cd ios
        bundle install
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
